name: Build CSGO-LOCAL

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: sync-test

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution
      run: msbuild CSGOLocal.sln /p:Configuration=Release /p:Platform=x86

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled-mod
        path: |
          **/Release/*.dll
          **/Release/*.exe
